### PR TITLE
add Indonesian translation

### PR DESCRIPTION
**Pull request by 39-chan**
I've translated the translation file (from English) into my language

[in-id.all.zip](https://github.com/NyaaPantsu/nyaa/files/1199915/in-id.all.zip)

### CODE REVIEW

**Comment by Lamppostmanufacturer** [comment]
Thank you for your contribution, translations are always welcome.
There are some issues with your pull request essentially bringing dev to master but the developers will resolve that.
Your translation file has a little issue with formatting since a JSON file will read the " in your string translation as code and not as the actual quotation marks. I recommend you use ' for putting words into a quote. If you want i can fix the file up for you.

**Comment by akuma06** [comment]
@Lamppostmanufacturer I don't see the actual translation file in the PR, can you confirm it?

**Comment by Lamppostmanufacturer** [comment]
I refered to the file he put in his comment, its not in the PR itself. I fixed the JSON issues here: 
[in-id.all.json.zip](https://github.com/NyaaPantsu/nyaa/files/1200445/in-id.all.json.zip)
In theory i could also put the same file into a pull request and credit 39-chan

**Comment by akuma06** [comment]
If you can PR it that would be awesome, I can't checkout of my branch now :')

**Pull request closed without merging**
