### PR TITLE
Account theme switcher (Pls merge)

### PR DESCRIPTION
**Pull request by steindornatorinn**
As mentioned in #721.

I've implemented the theme switching in the same way that the languages are, (reads first from account settings, reads cookie if that's not available) so actually having this in the account settings is unnecessary since it works for visiting users as well.

### CODE REVIEW

**Comment by tomleb** [comment]
I feel like this should be on the same page as /language and could be renamed /settings for local settings. Also should probably be added to the user setting page.

**Comment by steindornatorinn** [comment]
I agree, that would make a lot of sense.

**Comment by steindornatorinn** [comment]
I'm calling this ready for merge. These features are not integrated into the account settings yet but it's mostly because that page is in a bit of a disarray right now and this PR is already large enough.

**Comment by akuma06** [comment]
Might need @kipukun approval before merging =)

**Comment by kipukun** [comment]
All good!

**Pull request merged**
