### PR TITLE
Add tree-view file list (Done)

### PR DESCRIPTION
**Pull request by ElegantMonkey**
Add a tree-view like structure to the file list on the View Torrent page (https://imgur.com/a/2euzZ). Folders can open and collapse, with JS. I don't know if it works on mobile though, probably not.

~~if i write html again i will end myself~~

### CODE REVIEW

**Comment by kipukun** [comment]
#723

**Comment by ElegantMonkey** [comment]
I guess I'll _just wait™_ then.

**Comment by kipukun** [comment]
But otherwise the backend code is fine. Thank you for your work <3

**Comment by ewhal** [comment]
Just change the title and/or highlight one of the devs on irc when it's ready to be merged

**Pull request merged**
