### PR TITLE
Major improvement of navbar css (Ready for merge)

### PR DESCRIPTION
**Pull request by steindornatorinn**
Significantly improved the structure of the navbar and documented this properly so styling should be a breeze.

### CODE REVIEW

**Comment by akuma06** [comment]
Is it normal that I have the member link not inline with the rest?

**Comment by steindornatorinn** [comment]
No, definitely not. What browser are you using?

**Comment by akuma06** [comment]
Chrome Version 58.0.3029.110 (64-bit)

**Comment by steindornatorinn** [comment]
Seems very strange, I have the same setup and it looks fine. I'll have to look into it further, from the screenshot it looks like it's a collapsing margin issue.

I'll mark this PR as a WIP for now.

**Comment by mitki** [comment]
Same issue on Firefox 53.0.3 (64-bit). 

screenshot

**Comment by steindornatorinn** [comment]
Can I get one of you guys to help me investigate this? I have tried this on all major browsers (IE11, Chrome, FF) on both windows and GNU/Linux and I have had no luck in reproducing the issue. Nor can I find anything that should be causing it in the code.

**Comment by steindornatorinn** [comment]
Found the issue, I was running out of date HTML. Changing the status to ready for merge.

**Pull request merged**
