### PR TITLE
Move translation func to template variables

### PR DESCRIPTION
**Pull request by ElegantMonkey**
Apparently [template.ExecuteTemplate doesn't lock the templates' FuncMap](golang.org/src/text/template/exec.go?s=5133:5197#L181), meaning that the FuncMap can change during the template execution. As the current translation method is changing the translation func on the FuncMap, this means the language can change too.

Hopefully this will fix the bug with mixed translations on the site.

### CODE REVIEW

**Comment by yiiTT** [comment]
Captcha is broken with this pull
```
template: _captcha.html:5:32:
executing "captcha" at <$.T>:
can't evaluate field T in type
router.UploadForm
```

**Comment by ElegantMonkey** [comment]
@yiiTT, sorry, should be fixed with #661. Is it the only broken thing you've noticed?

**Comment by ElegantMonkey** [comment]
Or... nevermind, it's still broken on the other pages. I'll look at it.

**Comment by yiiTT** [comment]
@ElegantMonkey looks like there is still some issues everywhere else _captcha is used for Commenting and Registering,

**Comment by ElegantMonkey** [comment]
@yiiTT Yeah, I've seen it - I'll add a template function to bundle the CaptchaID and the Tfunc on a struct, which _captcha will use. Aside from this, anything else?

**Comment by yiiTT** [comment]
@ElegantMonkey nope that should be it, captcha is used for registering, commenting, and uploading.

**Pull request merged**
