### PR TITLE
New logo and background colors for sukebei

### PR DESCRIPTION
**Pull request by xhocquet**
References https://github.com/ewhal/nyaa/issues/441

Hey guys! Trying to help out to restore Nyaa, lots of good memories from the old site. Once I warm up to Go and the framework, I'll hopefully be able to provide more substantial work (I develop in Rails for work). Here's my first go at making sukebei a bit more obvious. I also added in a background color for the regular pages to give it some life (I can totally undo the regular index if it's too much). I drew color inspiration from the nyaapantsu logo:

## Normal
screen shot 2017-05-15 at 11 21 47 pm

## Sukebei
screen shot 2017-05-15 at 11 21 18 pm

The logo I just grabbed from the issue, I'm not great at graphics so I hope someone could give add a better version!

Also worth noting that the template function `Sukebei` doesn't work in dev. Does that have to do with the fact that I didn't import the DB, or is the toggle just not accurate in dev?

### CODE REVIEW

**Comment by sfan5** [comment]
\>slightly lewd renchon
oh no you didn't

**Comment by hazzzy** [comment]
DELET

**Comment by akuma06** [comment]
Might as well wait for @tomleb to finish his PR before merging this?

**Comment by xhocquet** [comment]
@alucard0134 Reason for closure? Sukebei styling is still something that is requested https://github.com/NyaaPantsu/nyaa/issues/441

**Comment by alucard0134** [comment]
accidental sorry

**Pull request closed without merging**
