### PR TITLE
Move scrape results to separate table

### PR DESCRIPTION
**Pull request by sfan5**
-> #943

page display and scraper tested and works
anything related to ES is <b>untested</b>

schema:
```sql
CREATE TABLE scrape (
	torrent_id       INTEGER NOT NULL,
	seeders          INTEGER NOT NULL,
	leechers         INTEGER NOT NULL,
	completed        INTEGER NOT NULL,
	last_scrape      TIMESTAMP NOT NULL,
	PRIMARY KEY (torrent_id),
	FOREIGN KEY (torrent_id) REFERENCES torrents(torrent_id)
);

CREATE TABLE sukebei_scrape (
	torrent_id       INTEGER NOT NULL,
	seeders          INTEGER NOT NULL,
	leechers         INTEGER NOT NULL,
	completed        INTEGER NOT NULL,
	last_scrape      TIMESTAMP NOT NULL,
	PRIMARY KEY (torrent_id),
	FOREIGN KEY (torrent_id) REFERENCES sukebei_torrents(torrent_id)
);

CREATE INDEX scrape_torrent_id_idx ON scrape (torrent_id);
CREATE INDEX sukebei_scrape_torrent_id_idx ON sukebei_scrape (torrent_id);
```

migration: (unsupported on sqlite)
```sql
INSERT INTO scrape(torrent_id, seeders, leechers, completed, last_scrape) SELECT torrent_id, seeders, leechers, completed, last_scrape FROM torrents WHERE last_scrape IS NOT NULL;
ALTER TABLE torrents DROP COLUMN seeders;
ALTER TABLE torrents DROP COLUMN leechers;
ALTER TABLE torrents DROP COLUMN completed;

INSERT INTO sukebei_scrape(torrent_id, seeders, leechers, completed, last_scrape) SELECT torrent_id, seeders, leechers, completed, last_scrape FROM sukebei_torrents WHERE last_scrape IS NOT NULL;
ALTER TABLE sukebei_torrents DROP COLUMN seeders;
ALTER TABLE sukebei_torrents DROP COLUMN leechers;
ALTER TABLE sukebei_torrents DROP COLUMN completed;
```

### CODE REVIEW

**Comment by ewhal** [comment]
should be "stats" instead of "scrape"

**Comment by sfan5** [comment]
the BitTorrent protocol literally calls this `scrape` tho

**Comment by akuma06** [comment]
`INSERT INTO scrape(seeders, leechers, completed, last_scrape, torrent_id) SELECT seeders, leechers, completed, last_scrape, torrent_id FROM torrents;`

This is the migration code. However, old torrents have null on seeders; leechers, completed and last_scrape. So you should make the scrape table accept Null

**Comment by sfan5** [comment]
The scrape table shouldn't contain NULL, how about this instead:
`INSERT INTO scrape(seeders, leechers, completed, last_scrape, torrent_id) SELECT seeders, leechers, completed, last_scrape, torrent_id FROM torrents WHERE last_scrape IS NOT NULL;`

**Pull request merged**
