### PR TITLE
"No API token" message if no API token, small changes

### PR DESCRIPTION
**Pull request by Kiloutre**
API token could be empty at times so it looked off in the user edit form to have the empty space
- " No API token" message if no API token
- Move "delete user" button to the right of the box, reducing the chances of a missclick
- Prettier tomorrow color on hovered button that actually are \<a\>

### CODE REVIEW

**Comment by Kiloutre** [comment]
@akuma06 I'm trying to get access of the T("") function from within template_function.go, in order to have formatThemeName(name string) return a translation string if it exists (e.g. themes_classic returning "nyaa.se (Beta)"), however after multiple tries i'm not getting any success
Any idea as to how do i proceed?

**Comment by akuma06** [comment]
Why do you need that ? Can't you just use the translation directly ?
I'm asking this because using directly the translation function would mean initializing it again. It's not very efficient. That's why I would like to know what do you want to do exactly.

**Comment by Kiloutre** [comment]
I wanna be able to have translation names "harcoded" into en_us.json for quick addition or deletion (or translation too), while also having a function that will format the name should no translation string exists (e.g. "**g** becomes **/g/**", because no one would do a one letter theme for any other reason)
It's not like i can rely on the automatic naming when i have theme names like "nyaa.se (Beta)" so i thought i would use the translation function to check if "themes_classic", "themes_g" or such exists and if it does return the translation

**Comment by akuma06** [comment]
You can do the same as https://github.com/NyaaPantsu/nyaa/blob/10a70e16c9f8b22eef1adb39b1e20f985c678f52/templates/template_functions.go#L242
You just pass as an argument the T function and the string.

**Review by yiiTT — APPROVED** [review]

**Pull request merged**
