### PR TITLE
Playbook to install latest nyaa straight from github

### PR DESCRIPTION
**Pull request by tomleb**
Was reverted because of the whole es config drama.

### CODE REVIEW

**Comment by tomleb** [comment]
Before merging: The current behavior is that if some changes were made in the directory of the build previously and you're trying to run this script, it won't work.
I can add force: yes to ansible, but that will erase all changes that were made.
Which behavior do we want ?
I could also modify it to make a backup of the current folder before getting the new one.

**Comment by akuma06** [comment]
3rd, then 2nd and last 1st I would say

**Comment by tomleb** [comment]
# Don't merge yet
I'll modify it to make a backup of the current folder before pulling latest.

**Comment by tomleb** [comment]
I make a backup of the folder now before pulling the latest.

# Ready to be merged

**Pull request merged**
